### ISSUE TITLE
Make ReplIO control the javaSource and helpGUI

### ISSUE THREAD

**Issue by Dierk** [Frege/frege-repl#29]
In the JavaFX version of the repl, I have to display GUIs for the javaSource and the help differently from other repls, namely in JavaFX controls. ATM this means that I have to duplicate pretty much all of the repl-core code. But I could reuse the code much more easily, if the ReplUI class demanded functions to open the help or java view.

The code under
https://github.com/Frege/frege-repl/blob/master/frege-repl-core/src/main/frege/frege/repl/FregeRepl.fr#L115-L117
would then use the ReplUI.showJavaView / helpView function provided by the ReplIO.

Would it be ok to do such a change?

**Comment by mmhelloworld** [comment]
Hi Dierk,

That's what the `print` function is supposed to do and it is meant to be implemented by the consumers of the REPL. For example, if you take a look at the code ([Frege Servlet](https://github.com/Frege/try-frege/blob/master/try-frege-repl/src/main/frege/tryfrege/repl/FregeReplServlet.fr#L34)) for the online REPL, it implements `print`  so that all the output (including the "help" and "java source" views) can be displayed on the browser.

I understand your concern which I think can be fixed by refactoring the code that does the evaluation into a separate function so that the code doesn't have to be duplicated for every view of the REPL. All the other cases of the `print` function should be implemented for every view.

The ReplIO class is, at the moment, very generic which supports only 3 functions: read, write and execute so I don't think it is a good idea to add these specific tasks like "help" view and "java source" view to that class. We might add more features for the REPL and we can't keep changing on that class. What do you think?

**Comment by Dierk** [comment]
Hi Marimuthu,

thanks for pointing me to the Servlet. That helped me understanding why my first attempt of shadowing `print` did not work. I need to shadow the callers as well - and this is where the ripple-effect starts. I need to overwrite the `repl` function and `loop`. It gets worse when I also want to adapt the general `cmdHelp` because that means shadowing `eval` and `help`.
However, I have it now working without too much trouble.

I agree to your point about clean and small responsibilities for the ReplIO class. I wonder whether we should introduce a "Printer" type class where a user of the repl-core can implement how he wants to handle printJavaSource, printHelp, etc.

Cheers and thanks for your great work
--Dierk
